### ISSUE TITLE
Using outside Symfony

### ISSUE THREAD

**Issue by khrizt** [theofidry/AliceDataFixtures#133]
Hi,

I know this is not an issue, but as this library is listed in [alice](https://github.com/nelmio/alice) as Framework agnostic, I wanted to ask, can this be used without symfony?

If that's the case, I have seen no documentation on how to use it in other frameworks.

Thanks

**Comment by theofidry** [comment]
Hi,

Yes Symfony is totally optional! That said I never had to use it outside of Symfony and traditionally most of it was coming from AliceBundle, hence the symfony support and more symfony oriented doc.

It however will work just fine without. The only thing might be that the DX is not idea. In alice you can find https://github.com/nelmio/alice/blob/master/src/Loader/NativeLoader.php which helps you when you just want something "that works" without any dependency injection container or anything. Here since there was no case for it, there is nothing of the sort. So you might need to do a bit more work by instantiating the right classes.

**Comment by khrizt** [comment]
Thanks for the reply. I have already configured and working alice in my project, but I've been looking at the symfony bundle code to reproduce the initial setup but I can't find my way on the code. Can you give me some hints on where I should start and I'll try to configure and make a documentation for a framework-agnostic way.

**Comment by theofidry** [comment]
From a brief view:

```php
new PurgerLoader(
    new PersisterLoader(
         new SimpleLoader(new FilesLoader()),
         new Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister()
    ),
    new Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\Purger(),
    'TRUNCATE',
    new NullLogger(),
)
```

Might need some tweaking but the idea should be there

**Comment by khrizt** [comment]
Great, I'll try it and comment about progress/results. Thanks a lot!

**Comment by khrizt** [comment]
Hey thanks for your help but finally I'm using alice directly with Doctrine data fixtures. Anyway thanks a  lot and keep the great work!
