### ISSUE TITLE
Still has `missing an assigned ID for field  'id'` bug

### ISSUE THREAD

**Issue by videni** [theofidry/AliceDataFixtures#151]
```
"Entity of type App\Component\Media\Model\Asset is missing an assigned ID for field  'id'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly."
```

this bug is supposed to be fixed at [#135](https://github.com/theofidry/AliceDataFixtures/pull/135)

Version
```
autelook/alice-bundle                          2.7.3              Symfony bundle to manage fixtures with Alice and Faker.
nelmio/alice                                    3.7.1              Expressive fixtures generator
theofidry/alice-data-fixtures                   1.3.0              Nelmio alice extension to persist the loaded fixtures.
```

```
  <entity name="Xiaolvmo\Component\Media\Model\AbstractAsset" table="app_media_asset">
        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>

        <field name="path" column="path" type="string" nullable="false" />
</entity>
```

**Comment by benja-M-1** [comment]
Hey @videni 👋🏻 I stumbled upon the same issue, what is your Driver?

I use pgsql, and this is important to notice because with PG the identifier generator is the `SequenceGenerator` which is execute before inserting any data. 
I found out that, when some relationship between entities are configured to be persisted, then the related entities receives an Id from the generator.
Then, [because there is an id generator AND the id for this entity has a value](https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php#L65), [the `ObjectManagerPersister` changes the id generator to TYPE_NONE](https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php#L131) (which does nothing). 
I managed to fix this surrounding this condition by making sure the entity is not already managed by doctrine, which means that doctrine already persisted it successfully. 

```diff
+if (!$this->objectManager->contains($object)) {
      // Check if the ID is explicitly set by the user. To avoid the ID to be overridden by the ID generator
      // registered, we disable it for that specific object.
      if ($metadata instanceof ORMClassMetadataInfo) {
          if ($metadata->usesIdGenerator() && false === empty($metadata->getIdentifierValues($object))) {
              $metadata = $this->configureIdGenerator($metadata);
          }
      } elseif ($metadata instanceof ODMClassMetadataInfo) {
          // Do nothing: currently not supported as Doctrine ODM does not have an equivalent of the ORM
          // AssignedGenerator.
      } else {
          // Do nothing: not supported.
      }
+}
```

@videni can you test that doing so would solve your issue?
@theofidry I read that [you have a plan](https://github.com/theofidry/AliceDataFixtures/pull/135#issuecomment-703911433). and this fix does not fixes the case when we explicitly set an ID in the fixtures. However do you want me to make a PR with this?

**Comment by yakobe** [comment]
@benja-M-1 This magically solves my problem too 😮 🎉. Pleeeease make a PR 😸 

I seem to have worked out what was causing my issue. I load the fixtures using some initial objects from the db:

```php
$this->fixtureLoader->load(
    $demoFixtureFiles,
    [],
    $initialObjects,
    PurgeMode::createNoPurgeMode()
);
```

These objects are already persisted and therefore have ID's etc. Your patch above means that they will not try to be persisted again.

@theofidry can we have this? Pretty please? 😄

**Comment by benja-M-1** [comment]
@yakobe Glad to read this! I made a PR :) cc @theofidry
