### ISSUE TITLE
Loader doesn't flush fixtures by file

### ISSUE THREAD

**Issue by SpartakusMd** [theofidry/AliceDataFixtures#49]
Hello, I'm using the hautelook/AliceBundle in my Symfony projects. It uses this package theofidry/AliceDataFixtures.

Now looking at the [nelmio/alice](https://github.com/nelmio/alice) documentation, specifically at [relations handling](https://github.com/nelmio/alice/blob/2.x/doc/relations-handling.md), we see that in order to use the auto-generated id of an entity we need to have the base fixture in a separate file :

> You can reference entities' ID but you will then have to split fixtures in multiple files (this is because objects are persisted at the end of each file processing)

When looking at `\Fidry\AliceDataFixtures\Loader\PersisterLoader::load()` we see that all the files are loaded at the same time and when using `@user_1->id` in the fixtures I get null.

From my understanding, the call of `$this->loader->load()` should be done in a foreach per `$fixturesFiles`. Is that correct ?

Could you release a fix for this ?

P.S. I will try to come with a PR if I'll get some free time, at the moment I have hardcoded the ID's.

**Comment by theofidry** [comment]
Granted it might be a bit confusing but the versions are:

- HautelookAliceBundle 2.x
- FidryAliceDataFixtures 1.x
- NelmioAlice 3.x

and:

- HautelookAliceBundle 1.x
- NelmioAlice 2.x

Depending of which version you are using, things are working differently. The doc you linked is for alice 2.x where alice load a file and persist its content. HautelookAliceBundle 1.x is then just finding all the files and calling alice for each of them.

In the newer versions, things are done a bit differently to be more robust: alice loads all the objects first and then FidryAliceDataFixtures takes care of persisting them. HautelookAliceBundle is becoming just about discovering the files to load.

In any case, it's a bit tricky to retrieve an ID if it's an auto-generated ID... By design your object is not meant to be fully manipulated until it has been persisted. Either rely on relations e.g. `$group->addUser($user)` instead of `$group->addUser($userId)` or use UUIDs.

**Comment by SpartakusMd** [comment]
@theofidry, yeah, you're right, I copied the bad link. I compared the 3.x with 2.x documentation and it's the same. I think the docs should be updated.

In my case I can't use a relation and I need only the ID, so for the moment I hardcoded it.

Anyways, it was a great feature and should be kept.

**Comment by theofidry** [comment]
Could you open an issue on alice for the doc? Thanks :)

>Anyways, it was a great feature and should be kept.

It was also causing _a lot_ of issues with serious limitations, which is one reason for the change. You could keep using the IDs like that, but that means:

- you have zero guarantee the ID is available in the DB (by design)
- you need to make your IDs settable or write a custom hydrator to modify the ID using reflection to avoid to have a setter
- you need to disable Doctrine ID generator (cf. https://github.com/theofidry/AliceDataFixtures/issues/40)

**Comment by SpartakusMd** [comment]
Issue created : https://github.com/nelmio/alice/issues/785
