### ISSUE TITLE
Detached document cannot be removed

### ISSUE THREAD

**Issue by olvlvl** [theofidry/AliceDataFixtures#51]
Hi,

`ObjectManagerPersister::flush()` is also invoking `ObjectManager::clear()` which is super annoying because fixtures are removed from the identity map and when I try to remove them I get the following message:

```
Doctrine\ODM\MongoDB\MongoDBException: Detached document cannot be removed
```

I never had this issue with `nelmio/alice` v2.0. Is it a bug or a feature? Does `clear()` need to be invoked? How can I fix my tests?

**Comment by theofidry** [comment]
To be honest I'm not dead set on it, so it's open to discussion... 

The reasoning is as you load X files in one test, X files in another and so on, you actually get a significant performance issue due to memory leak. But maybe the user experience is less pleasant by doing so as it does mean you get brand new objects no longer managed by doctrine.

A solution would be to add a parameter to the constructor like `clearOnFlush` and if the user want he can override the service definition to enable that feature.

**Comment by olvlvl** [comment]
I don't know how other people do, by I just do `dropCollections()` to reset stuff when I need to.

**Comment by theofidry** [comment]
That's for Doctrine ODM isn't it?

**Comment by olvlvl** [comment]
Sorry, I edited my comment. Yes, it's for Doctrine/MongoDB.

**Comment by olvlvl** [comment]
No, it's not. It's just dropping the collection, keeping whatever is managed alive and well.

**Comment by theofidry** [comment]
Fair enough. Let's remove that then :)

**Comment by olvlvl** [comment]
I'll submit a PR right away!
