### ISSUE TITLE
Symfony requirement for test

### ISSUE THREAD

**Issue by Soullivaneuh** [theofidry/AliceDataFixtures#66]
Reaction for https://github.com/liip/LiipFunctionalTestBundle/pull/337#issuecomment-340817002

IMHO, the needed symfony components should be required on dev env for test, especially for `prefer-lowest` state.

At least or in addition, the supported Symfony version should be clearly indicated on the [documentation](https://github.com/theofidry/AliceDataFixtures#symfony).

Also, there is not test for 2.7 and 2.8 LTS, is it wanted? Is it officially supported or not? Since 3.4 is the next LTS, we may not support the older.

BTW, did you here about this testing packages?

- https://packagist.org/packages/matthiasnoback/symfony-dependency-injection-test
- https://packagist.org/packages/matthiasnoback/symfony-config-test

They are very useful for this kind of tests. :wink: 

WDYT?

**Comment by theofidry** [comment]
Symfony _is_ required as a dev dependency, simply not in the main `composer.json`: [see here](https://github.com/theofidry/AliceDataFixtures/blob/master/vendor-bin/symfony/composer.json).

The reason is that this library has multiple bridges, if you require everything together:

- you are not really testing the bridges in isolation
- you are much more likely to have a hard conflict as a maintainer but unlikely to happen to the user (unless for example he tries to install both Symfony and Laravel or something like that, but that's very very edge case)
- you create a greater diff between what you test and what you're user may end up with. To illustrate if you have `symfony/yaml:  ^2.8 || ^3.0` in require but a dev package has `symfony/yaml: ^3.0` then you cannot test your library for `symfony/yaml [2.8.0 ; 3.0.0[`. The current split technique doesn't prevent this from happening, but reduce its likelihood a lot

>the supported Symfony version should be clearly indicated on the documentation.

Yes it could be added, same for Alice and Hautelook as well. My current policy is 3.3.0 and 3.4.0 once it's out. For the older I'm ok with supporting it, I just don't want to work on it.

The two testing packages are interesting, but I already wrote the tests before seeing them and I didn't have much interest in re-writing it :)

**Comment by Soullivaneuh** [comment]
> Symfony is required as a dev dependency, simply not in the main composer.json: see here.

What is `vendor-bin`? Oo

> Yes it could be added, same for Alice and Hautelook as well. My current policy is 3.3.0 and 3.4.0 once it's out. For the older I'm ok with supporting it, I just don't want to work on it.

Well, IMO at least one LTS should be supported, so I guess supporting 3.4 on your stable release will be ok. :+1: 

> The two testing packages are interesting, but I already wrote the tests before seeing them and I didn't have much interest in re-writing it :)

Understandable, maybe I'll get the time for a POC one day. :wink:

**Comment by theofidry** [comment]
> What is `vendor-bin`?

See [bamarni/composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin) which I'm using a lot lately. I'm not sure about a doc entry in the doc for it as I would need to do so for every project, instead I make sure to provide an understandable `Makefile`, just type `make` and all the magic happens and it's self-documented

**Comment by Soullivaneuh** [comment]
Ok, so I think the only thing to do to close this issue is the clear dependency support info on the documentation.

**Comment by theofidry** [comment]
I'll try to write a blog post about it at some point and link it as I really don't want to repeat myself to much for the stuff which I use in at least... 5 repositories (OSS) so far

**Comment by theofidry** [comment]
Meanwhile I'll close this one :)

**Comment by Soullivaneuh** [comment]
> Meanwhile I'll close this one :)

But what about telling the version support here? https://github.com/theofidry/AliceDataFixtures#symfony :stuck_out_tongue:

**Comment by theofidry** [comment]
Yes I'll add an entry for the supported drivers & frameworks
